import os
import asyncio
import datetime
import time
from fastapi import FastAPI, HTTPException, BackgroundTasks, WebSocket, WebSocketDisconnect, Form, Response
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from livekit import api
from .converters.rvc_stream import RVCStreamingConverter
from .converters.dummy import DummyVoiceConverter
from .noise.noise_suppressor import WebRTCNoiseSuppressor
from .pipeline import VoiceConversionWorker

# Load environment variables
load_dotenv()

app = FastAPI(title="Keira MVP Voice Conversion Server")

# Configure CORS
# allow_origins=["*"] and allow_credentials=True cannot be combined (browsers reject it).
# Use explicit origin list for credentialed requests; fall back to "*" only for non-credentialed.
CORS_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ORIGINS", "*").split(",")
    if origin.strip()
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=(CORS_ORIGINS != ["*"]),
    allow_methods=["*"],
    allow_headers=["*"],
)

LIVEKIT_URL = os.getenv("LIVEKIT_URL", "ws://localhost:7880")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")

# RVC serverless GPU configuration
RVC_ENDPOINT_URL = os.getenv("RVC_ENDPOINT_URL")
RVC_API_KEY = os.getenv("RVC_API_KEY", "")
RVC_PITCH_SHIFT = int(os.getenv("RVC_PITCH_SHIFT", "0"))
# Blend between FAISS-retrieved target-voice timbre (1.0) and raw HuBERT content
# features (0.0), which still carry some of the original speaker's own vocal-tract
# characteristics. Bumped from RVCStreamingConverter's 0.75 default (2026-07-03
# experiment: live streamed calls sound less like the trained voice than the offline
# `modal run` one-shot test, which uses the same 0.75 default -- so this alone isn't
# confirmed as the cause, but it's cheap/reversible to test). Env var, not another
# code deploy, so it can be re-tuned from Render without touching code again.
RVC_INDEX_RATE = float(os.getenv("RVC_INDEX_RATE", "0.75"))
RVC_F0_METHOD = os.getenv("RVC_F0_METHOD", "pm")  # pm (parselmouth) or rmvpe

# Twilio Configuration
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")
# TWILIO_SIP_TRUNK_ID: LiveKit SIP Outbound Trunk ID (created via /api/setup).
# Not a Twilio resource ID — generated by LiveKit when you configure it to call out via Twilio.
TWILIO_SIP_TRUNK_ID = os.getenv("TWILIO_SIP_TRUNK_ID")
# TWILIO_SIP_URI: Termination URI of your Twilio Elastic SIP Trunk (e.g. myproject.pstn.twilio.com).
# Used once by /api/setup to create the LiveKit outbound trunk. Not needed at call time.
TWILIO_SIP_URI = os.getenv("TWILIO_SIP_URI")
# SIP credentials matching the Twilio Elastic SIP Trunk Credential List (set once via /api/setup)
TWILIO_SIP_USERNAME = os.getenv("TWILIO_SIP_USERNAME", "Keira")
# Do NOT hard-code a fallback password — require it to be set explicitly in env vars.
TWILIO_SIP_PASSWORD = os.getenv("TWILIO_SIP_PASSWORD", "")
# Public URL of this server — used by /api/setup to configure Twilio's inbound webhook.
SERVER_URL = os.getenv("SERVER_URL")

# Initialize Twilio Client optionally
twilio_client = None
if TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN:
    try:
        from twilio.rest import Client
        twilio_client = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
    except Exception as e:
        print(f"[Server Warning] Failed to initialize Twilio client: {e}")

# Global tracking
active_workers = {}
active_calls = {}


async def _restrict_sip_audio(room_name: str, sip_identity: str = "sip-lead"):
    """
    Option A — Server-side SIP track isolation.

    LiveKit's SIP bridge runs server-side and ignores browser-level
    setTrackSubscriptionPermissions(), so the SIP participant always receives
    a mix of EVERY audio track in the room — including the agent's raw mic.
    The lead would hear the real agent voice on top of the converted Keira voice.

    This helper uses LiveKit Room Service update_subscriptions() to explicitly
    unsubscribe the SIP participant from the raw agent mic track so they ONLY
    hear the bot's converted-audio track.

    For outbound calls sip_identity is always "sip-lead" (set explicitly in
    create_sip_participant). For inbound calls, LiveKit assigns a dynamic identity
    from the caller's SIP URI — so we detect the SIP participant by exclusion:
    whoever is NOT a voice-converter-bot and NOT an agent browser participant.

    Retries up to max_attempts times to handle the window where the agent browser
    and/or SIP participant hasn't joined yet.
    """
    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        return

    max_attempts = 8
    retry_delay = 2.0  # seconds between attempts

    for attempt in range(1, max_attempts + 1):
        await asyncio.sleep(retry_delay)
        lk = None
        try:
            lk = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
            resp = await lk.room.list_participants(
                api.ListParticipantsRequest(room=room_name)
            )

            # Categorise every participant in the room
            raw_agent_track_sids = []
            bot_track_sids = []
            resolved_sip_identity = None

            for p in resp.participants:
                identity = p.identity
                is_bot = identity.startswith("voice-converter-bot")
                is_agent = "agent" in identity.lower() and not is_bot
                # SIP participant: matches the known identity OR is neither bot nor agent
                is_sip = (identity == sip_identity) or \
                          (not is_bot and not is_agent and identity != sip_identity and
                           sip_identity not in ("sip-lead",))  # dynamic inbound detection

                # For outbound: trust the explicit sip_identity
                if identity == sip_identity:
                    resolved_sip_identity = identity

                # For inbound: the SIP participant identity is dynamic
                if sip_identity == "sip-caller" and not is_bot and not is_agent:
                    resolved_sip_identity = identity

                for t in p.tracks:
                    if t.type == 0:  # 0 = AUDIO
                        if is_bot:
                            bot_track_sids.append(t.sid)
                        elif is_agent:
                            raw_agent_track_sids.append(t.sid)

            if not resolved_sip_identity:
                print(f"[SIP Isolation] Attempt {attempt}: SIP participant not yet in room — retrying...")
                continue

            if not raw_agent_track_sids:
                print(f"[SIP Isolation] Attempt {attempt}: No raw agent tracks found yet — retrying...")
                continue

            # Unsubscribe SIP participant from the raw agent mic track(s)
            await lk.room.update_subscriptions(
                api.UpdateSubscriptionsRequest(
                    room=room_name,
                    identity=resolved_sip_identity,
                    track_sids=raw_agent_track_sids,
                    subscribe=False,
                )
            )
            print(
                f"[SIP Isolation] ✅ '{resolved_sip_identity}' unsubscribed from raw agent "
                f"tracks {raw_agent_track_sids}. "
                f"Only bot converted tracks {bot_track_sids} will reach the phone."
            )
            return  # done

        except Exception as e:
            print(f"[SIP Isolation] Attempt {attempt} failed: {e}")
        finally:
            if lk:
                await lk.aclose()

    print(f"[SIP Isolation] ⚠️ Could not restrict SIP subscriptions for room {room_name} after {max_attempts} attempts.")


# Log Twilio configuration state at startup so misconfigurations are obvious in logs
def _log_config():
    print("=== Keira Server Configuration ===")
    print(f"  LiveKit URL:          {LIVEKIT_URL}")
    print(f"  LiveKit API Key:      {'SET' if LIVEKIT_API_KEY else 'MISSING ⚠️'}")
    print(f"  LiveKit API Secret:   {'SET' if LIVEKIT_API_SECRET else 'MISSING ⚠️'}")
    print(f"  Twilio Account SID:   {'SET' if TWILIO_ACCOUNT_SID else 'MISSING ⚠️'}")
    print(f"  Twilio Auth Token:    {'SET' if TWILIO_AUTH_TOKEN else 'MISSING ⚠️'}")
    print(f"  Twilio Phone Number:  {TWILIO_PHONE_NUMBER or 'MISSING ⚠️'}")
    print(f"  Twilio SIP URI:       {TWILIO_SIP_URI or 'not set (needed for /api/setup)'}")
    print(f"  LiveKit SIP Trunk ID: {TWILIO_SIP_TRUNK_ID or 'MISSING ⚠️  → run POST /api/setup to create'}")
    print(f"  Server URL:           {SERVER_URL or 'not set (needed for /api/setup webhook config)'}")
    print(f"  RVC Endpoint:         {RVC_ENDPOINT_URL or 'not set (using dummy converter)'}")
    print("==================================")

_log_config()

# WebSocket connection manager
class ConnectionManager:
    def __init__(self):
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        print(f"[WebSockets] Agent connected. Total agents: {len(self.active_connections)}")

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)
            print(f"[WebSockets] Agent disconnected. Total agents: {len(self.active_connections)}")

    async def broadcast(self, message: dict):
        for connection in self.active_connections:
            try:
                await connection.send_json(message)
            except Exception as e:
                print(f"[WebSockets Error] Failed to send message: {e}")

manager = ConnectionManager()

# Helper to derive the LiveKit SIP domain from LIVEKIT_URL
def get_livekit_sip_domain() -> str:
    from urllib.parse import urlparse
    try:
        parsed = urlparse(LIVEKIT_URL)
        host = parsed.netloc or parsed.path
        host = host.split(":")[0]  # strip port
        parts = host.split(".")
        if len(parts) >= 3 and parts[-2] == "livekit" and parts[-1] == "cloud":
            return f"{parts[0]}.sip.livekit.cloud"
    except Exception:
        pass
    return "sip.livekit.cloud"

# Shared logic to poll the RVC endpoint's /health until the Modal GPU reports "ready",
# used both by the manual /api/warmup endpoint and to block an outbound dial until the
# voice engine can actually convert audio. Never raises — always returns a status dict.
async def _wait_for_rvc_ready(max_wait_seconds: float = 360.0, poll_interval: float = 30.0) -> dict:
    if not RVC_ENDPOINT_URL:
        return {"status": "skipped", "message": "No RVC endpoint URL configured."}

    import httpx
    health_url = RVC_ENDPOINT_URL.replace("/convert", "/health").replace("web-convert", "web-health").replace("web_convert", "web_health")
    print(f"[RVC Warmup] Polling {health_url} (max_wait={max_wait_seconds:.0f}s, interval={poll_interval:.0f}s)")

    elapsed = 0.0
    async with httpx.AsyncClient(timeout=httpx.Timeout(35.0, connect=10.0)) as client:
        while elapsed < max_wait_seconds:
            try:
                resp = await client.get(health_url)
            except httpx.TimeoutException:
                elapsed += poll_interval
                print(f"[RVC Warmup] GPU not ready yet (timeout after {poll_interval:.0f}s). Retrying... ({elapsed:.0f}/{max_wait_seconds:.0f}s elapsed)")
                continue

            if resp.status_code == 200:
                data = resp.json()
                if data.get("status") == "loading":
                    elapsed += poll_interval
                    print(f"[RVC Warmup] GPU booting, model loading... Retrying... ({elapsed:.0f}/{max_wait_seconds:.0f}s elapsed)")
                    await asyncio.sleep(poll_interval)
                    continue
                print(f"[RVC Warmup] SUCCESS: {data}")
                return {"status": "success", "message": "GPU warmed up successfully.", "rvc_status": data}
            else:
                print(f"[RVC Warmup] FAILED: HTTP Status {resp.status_code} - {resp.text}")
                return {"status": "error", "message": f"RVC endpoint returned status code {resp.status_code}"}

    print(f"[RVC Warmup] TIMEOUT: GPU did not become ready within {max_wait_seconds:.0f}s")
    return {"status": "error", "message": f"GPU did not become ready within {max_wait_seconds:.0f}s."}

# Shared logic to spawn a converter bot for a room
async def _do_start_bot(room_name: str, background_tasks: BackgroundTasks, agent_gender: str = "male"):
    if room_name in active_workers:
        return {"status": "already_running", "message": f"Voice conversion bot is already active in room {room_name}."}

    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        raise HTTPException(status_code=500, detail="LiveKit server keys are not configured.")

    # Generate token specifically for the bot participant
    bot_identity = f"voice-converter-bot-{room_name}"
    bot_token = api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET) \
        .with_identity(bot_identity) \
        .with_name("Voice Conversion Bot") \
        .with_grants(api.VideoGrants(
            room_join=True,
            room=room_name,
            can_publish=True,
            can_subscribe=True
        )) \
        .with_ttl(datetime.timedelta(seconds=3600))
    
    # Choose voice conversion engine (priority: RVC > Dummy)
    # If RVC_PITCH_SHIFT is explicitly configured in the environment, respect it.
    # Otherwise, fall back to the gender-based lookup.
    if "RVC_PITCH_SHIFT" in os.environ:
        pitch_shift = RVC_PITCH_SHIFT
        print(f"[Server] Using explicit pitch shift from environment: {pitch_shift}")
    else:
        pitch_shift = 12 if agent_gender.lower() == "male" else 0
        print(f"[Server] Agent gender: {agent_gender} → pitch_shift={pitch_shift}")

    if RVC_ENDPOINT_URL:
        print(f"[Server] Spawning RVC Streaming Voice Changer (Endpoint: {RVC_ENDPOINT_URL})")
        converter = RVCStreamingConverter(
            endpoint_url=RVC_ENDPOINT_URL,
            api_key=RVC_API_KEY,
            pitch_shift=pitch_shift,
            index_rate=RVC_INDEX_RATE,
            f0_method=RVC_F0_METHOD,
        )
    else:
        print("[Server] No RVC endpoint config found. Spawning Dummy Pitch Modulation Engine.")
        converter = DummyVoiceConverter()

    # Initialize noise suppression (WebRTC)
    suppressor = WebRTCNoiseSuppressor(ns_level=3)

    worker = VoiceConversionWorker(
        room_url=LIVEKIT_URL,
        token=bot_token.to_jwt(),
        converter=converter,
        suppressor=suppressor,
    )

    active_workers[room_name] = worker

    # Fail-closed warm gate (Task 4): kick off a single background readiness probe
    # for the life of this worker. Twilio polls /api/call/wait every ~3s while a
    # caller is on hold, so worker.is_ready must be a cheap property read — not a
    # fresh network probe per poll. This background task calls the (potentially
    # slow) wait_until_ready() exactly once and caches the result.
    worker.start_readiness_probe(150.0)

    # Start bot in background
    async def run_worker_task():
        try:
            await worker.start()
            while worker.running:
                await asyncio.sleep(1.0)
        except Exception as e:
            print(f"[Server Error running bot] {e}")
        finally:
            active_workers.pop(room_name, None)
            await worker.stop()
            print(f"[Server] Bot cleaned up for room: {room_name}")

    # Kick off a GPU warm-up ping the instant the bot starts. Modal cold-starts the
    # T4 on the first request (~8-30s); firing /health now overlaps that cold start
    # with call setup and the lead's phone ringing, so the GPU is (nearly) warm by the
    # time the agent's first words arrive — instead of the cold start being added on
    # top of the first converted audio. Fire-and-forget; failures are non-fatal.
    if RVC_ENDPOINT_URL:
        async def _prewarm_rvc():
            try:
                import httpx
                health_url = (RVC_ENDPOINT_URL
                              .replace("/convert", "/health")
                              .replace("web-convert", "web-health")
                              .replace("web_convert", "web_health"))
                async with httpx.AsyncClient(timeout=120.0) as client:
                    await client.get(health_url)
                print("[Server] RVC pre-warm ping sent on bot start (overlaps GPU cold start with ringing)")
            except Exception as e:
                print(f"[Server] RVC pre-warm ping failed (non-fatal): {e}")
        asyncio.create_task(_prewarm_rvc())

    background_tasks.add_task(run_worker_task)
    return {"status": "started", "botIdentity": bot_identity}

class TokenRequest(BaseModel):
    roomName: str
    identity: str
    agentGender: str = "male"  # 'male' or 'female' — sets pitch shift automatically

@app.post("/api/token")
async def get_token(request: TokenRequest):
    """
    Brokers LiveKit client access tokens for browser web clients.
    """
    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        raise HTTPException(
            status_code=500, 
            detail="LiveKit API keys are not configured on the server."
        )
        
    try:
        token = api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET) \
            .with_identity(request.identity) \
            .with_name(f"Participant {request.identity}") \
            .with_grants(api.VideoGrants(
                room_join=True,
                room=request.roomName,
                can_publish=True,
                can_subscribe=True
            )) \
            .with_ttl(datetime.timedelta(seconds=3600))

        return {"token": token.to_jwt(), "serverUrl": LIVEKIT_URL}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/start-bot")
async def start_bot(request: TokenRequest, background_tasks: BackgroundTasks):
    """
    Spawns the real-time audio pipeline bot and connects it to the specified LiveKit room.
    """
    return await _do_start_bot(request.roomName, background_tasks, request.agentGender)

@app.post("/api/stop-bot")
async def stop_bot(request: TokenRequest):
    """
    Forces the voice conversion bot in a specific room to disconnect and clean up.
    """
    room_name = request.roomName
    worker = active_workers.get(room_name)
    if worker:
        await worker.stop()
        active_workers.pop(room_name, None)
        return {"status": "stopped", "message": f"Voice conversion bot stopped in room {room_name}."}
    return {"status": "not_running", "message": f"No active bot found in room {room_name}."}

# --- TWILIO & SIP INTEGRATION ENDPOINTS ---

class OutboundCallRequest(BaseModel):
    phoneNumber: str
    agentIdentity: str
    agentGender: str = "male"  # 'male' or 'female' — sets pitch shift automatically

@app.post("/api/call/outbound")
async def call_outbound(request: OutboundCallRequest, background_tasks: BackgroundTasks):
    """
    Triggered when an agent clicks "Call" to dial a lead.
    LiveKit dials the lead via its SIP outbound trunk (Twilio Elastic SIP Trunking),
    so the lead's phone appears as a SIP participant directly in the LiveKit room.
    This avoids the Twilio PV → LiveKit inbound SIP path that Twilio PV cannot reach.
    """
    import traceback as _tb

    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        raise HTTPException(status_code=500, detail="LiveKit API keys are not configured.")

    # Resolve the outbound SIP trunk ID.
    # Always do a live lookup first (by name) so a stale TWILIO_SIP_TRUNK_ID env var
    # never causes a 404 after /api/setup recreates the trunk.
    sip_trunk_id = None
    try:
        lk_tmp = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
        trunks = await lk_tmp.sip.list_outbound_trunk(api.ListSIPOutboundTrunkRequest())
        trunk = next((t for t in trunks.items if t.name == "Keira Twilio Outbound"), None)
        if trunk:
            sip_trunk_id = trunk.sip_trunk_id
            print(f"[Server] Resolved SIP trunk via live lookup: {sip_trunk_id}")
        await lk_tmp.aclose()
    except Exception as e:
        print(f"[Server] Live trunk lookup failed ({e}); falling back to env var.")

    # Fall back to the env var if the live lookup missed (e.g. name mismatch)
    if not sip_trunk_id:
        sip_trunk_id = TWILIO_SIP_TRUNK_ID

    if not sip_trunk_id:
        raise HTTPException(status_code=503, detail="No SIP outbound trunk found. Run /api/setup first.")

    room_name = f"outbound_{request.phoneNumber.replace('+', '').replace(' ', '')}_{int(time.time())}"

    # 1. Spawn the conversion bot (pass agent gender so pitch shift is correct)
    try:
        await _do_start_bot(room_name, background_tasks, request.agentGender)
    except HTTPException:
        raise
    except Exception as e:
        _tb.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to start conversion bot: {str(e)}")

    # 1b. Fail-closed warm gate: block until the converter's backend session can
    # actually accept audio before ringing the lead. The bot's own pre-warm ping
    # (fired inside _do_start_bot) starts the cold start, but a cold T4 can take
    # 60-90s to load the model. Unlike the old fail-open wait, we do NOT dial on
    # failure — publishing converted audio to a lead requires a ready GPU session
    # (the pipeline never falls back to raw voice; see pipeline.py), so an unready
    # engine here must abort the call, not proceed with silence.
    #
    # We await wait_for_readiness_probe() here rather than wait_until_ready()
    # directly: _do_start_bot already kicked off a background readiness probe
    # via worker.start_readiness_probe() with no `await` between that call and
    # this one, so a direct wait_until_ready() call here would open a *second*,
    # independent probe session racing the background one against the backend's
    # 1-concurrent-session limit — the loser gets {"type":"busy"} and reports
    # not-ready even when the GPU is actually warm. wait_for_readiness_probe()
    # instead awaits that same background task, so exactly one probe connection
    # is opened per outbound call.
    worker = active_workers.get(room_name)
    if not worker:
        # _do_start_bot() above sets active_workers[room_name] synchronously
        # before returning (it's a plain await, not a BackgroundTasks entry),
        # so reaching here with no worker is an invariant violation, not an
        # expected "not started yet" state.
        raise HTTPException(status_code=500, detail="Bot worker failed to initialize.")

    ok = await worker.wait_for_readiness_probe(150.0)
    if not ok:
        await worker.stop()
        active_workers.pop(room_name, None)
        raise HTTPException(
            status_code=503,
            detail="Voice engine not ready — GPU still warming. Try again shortly.",
        )

    # 2. LiveKit dials the lead via Twilio Elastic SIP Trunking.
    #    LiveKit → SIP trunk → Twilio → PSTN → lead's phone.
    #    The lead appears as a SIP participant in the LiveKit room directly.
    print(f"[Server] LiveKit SIP dial: {request.phoneNumber} via trunk {sip_trunk_id} → room {room_name}")
    lk = None
    try:
        lk = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)

        # Look up trunk to log what number it dials from
        try:
            trunks = await lk.sip.list_outbound_trunk(api.ListSIPOutboundTrunkRequest())
            trunk_info = next((t for t in trunks.items if t.sip_trunk_id == sip_trunk_id), None)
            if trunk_info:
                print(f"[Server] Trunk address: {trunk_info.address}, numbers: {list(trunk_info.numbers)}")
        except Exception:
            pass

        result = await lk.sip.create_sip_participant(
            api.CreateSIPParticipantRequest(
                sip_trunk_id=sip_trunk_id,
                sip_call_to=request.phoneNumber,
                room_name=room_name,
                participant_identity="sip-lead",
                participant_name="Lead",
            )
        )
        print(f"[Server] SIP participant created: id={result.participant_id} sip_call_id={result.sip_call_id}")
    except Exception as e:
        _tb.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to initiate SIP call: {str(e)}")
    finally:
        if lk:
            await lk.aclose()

    # 3. Fire-and-forget: unsubscribe the SIP lead from the raw agent mic track so
    # they ONLY hear the bot's converted Keira voice. The SIP bridge ignores
    # browser-level setTrackSubscriptionPermissions — this must be done server-side.
    asyncio.create_task(_restrict_sip_audio(room_name, sip_identity="sip-lead"))

    # Record active call details
    active_calls[room_name] = {
        "room_name": room_name,
        "from": TWILIO_PHONE_NUMBER or "Keira Outbound",
        "to": request.phoneNumber,
        "status": "in-progress",
        "direction": "outbound",
        "created_at": datetime.datetime.now().isoformat()
    }

    # 3. Generate access token for the agent
    agent_token = api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET) \
        .with_identity(request.agentIdentity) \
        .with_name(f"Agent {request.agentIdentity}") \
        .with_grants(api.VideoGrants(
            room_join=True,
            room=room_name,
            can_publish=True,
            can_subscribe=True
        )) \
        .with_ttl(datetime.timedelta(seconds=3600))

    return {
        "status": "initiated",
        "roomName": room_name,
        "token": agent_token.to_jwt(),
        "serverUrl": LIVEKIT_URL
    }

@app.post("/api/call/status-event")
async def call_status_event(
    CallSid: str = Form(default=""),
    CallStatus: str = Form(default=""),
    CallDuration: str = Form(default=""),
    To: str = Form(default=""),
    From: str = Form(default=""),
    ErrorCode: str = Form(default=""),
    ErrorMessage: str = Form(default=""),
):
    """Twilio status callback — logs every call state change so we can diagnose failures."""
    print(f"[Twilio Status] SID={CallSid} status={CallStatus} duration={CallDuration}s to={To} from={From} error={ErrorCode} {ErrorMessage}")
    return Response(status_code=204)

@app.post("/api/call/inbound")
async def call_inbound(
    background_tasks: BackgroundTasks,
    From: str = Form(...),
    CallSid: str = Form(...),
    To: str = Form(default=""),
    CallStatus: str = Form(default=""),
):
    """
    Twilio voice webhook for inbound calls.

    Flow:
      1. Return TwiML that puts caller on hold (plays ringing tone) and polls /api/call/wait
         every 3 seconds to check if agent has accepted.
      2. Agent accepts → /api/call/accept is called → active_calls[room]["status"] = "accepted"
      3. /api/call/wait detects acceptance → returns TwiML that bridges to LiveKit SIP.

    This avoids the previous bug where Twilio bridged to LiveKit before LiveKit was ready,
    causing an immediate SIP rejection and 2-4 second drops.
    """
    print(f"[Twilio Inbound] CallSid={CallSid} From={From} To={To} Status={CallStatus}")
    room_name = f"inbound_{CallSid}"

    # 1. Spawn conversion bot for this incoming call room
    await _do_start_bot(room_name, background_tasks)

    # 2. Record the inbound call
    active_calls[room_name] = {
        "room_name": room_name,
        "from": From,
        "to": To or TWILIO_PHONE_NUMBER or "Keira Inbound",
        "status": "ringing",
        "direction": "inbound",
        "call_sid": CallSid,
        "created_at": datetime.datetime.now().isoformat()
    }

    # 3. Broadcast incoming call to WebSockets (agent UI shows popup)
    await manager.broadcast({
        "event": "incoming_call",
        "roomName": room_name,
        "callerId": From,
        "callSid": CallSid
    })
    print(f"[Twilio Inbound] Broadcasted incoming_call event for room={room_name}")

    # 4. Return TwiML: put caller on hold and poll /api/call/wait until agent accepts
    wait_url = f"{SERVER_URL.rstrip('/') if SERVER_URL else ''}/api/call/wait?callSid={CallSid}"
    status_callback = f"{SERVER_URL.rstrip('/') if SERVER_URL else ''}/api/call/status-event"
    twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Pause length="60"/>
    <Hangup/>
</Response>"""
    # If SERVER_URL is set, use Gather/Redirect polling; otherwise fall back to immediate SIP bridge
    if SERVER_URL:
        twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Redirect method="POST">{wait_url}</Redirect>
</Response>"""
    else:
        # Fallback: immediate SIP bridge (old behaviour) when SERVER_URL is not configured
        sip_domain = get_livekit_sip_domain()
        twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial timeout="30" action="{status_callback}" method="POST">
        <Sip>sip:{room_name}@{sip_domain};transport=tcp</Sip>
    </Dial>
</Response>"""
    print(f"[Twilio Inbound] Returning TwiML for CallSid={CallSid}")
    return Response(content=twiml, media_type="application/xml")


@app.post("/api/call/wait")
async def call_wait(
    callSid: str,
    CallSid: str = Form(default=""),
    CallStatus: str = Form(default=""),
):
    """
    Polling endpoint called by Twilio every few seconds while caller is on hold.
    Returns hold TwiML until the agent accepts, then returns the SIP bridge TwiML.
    """
    # callSid can come from query param (our redirect) or Twilio form POST
    sid = callSid or CallSid
    room_name = f"inbound_{sid}"
    print(f"[Twilio Wait] Polling for callSid={sid} room={room_name} TwilioStatus={CallStatus}")

    call_info = active_calls.get(room_name)
    worker = active_workers.get(room_name)
    if call_info and call_info.get("status") == "accepted" and worker and worker.is_ready:
        # Agent has accepted AND the voice engine is confirmed ready — bridge to
        # LiveKit SIP. Fail-closed: if the worker isn't ready yet, this falls
        # through to the hold-TwiML branch below and re-polls in 3s rather than
        # bridging a call that would only publish silence (never raw audio).
        sip_domain = get_livekit_sip_domain()
        status_callback = f"{SERVER_URL.rstrip('/') if SERVER_URL else ''}/api/call/status-event"
        print(f"[Twilio Wait] Agent accepted! Bridging to LiveKit SIP: {room_name}@{sip_domain}")
        twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial timeout="60" action="{status_callback}" method="POST">
        <Sip>sip:{room_name}@{sip_domain};transport=tcp</Sip>
    </Dial>
</Response>"""
        return Response(content=twiml, media_type="application/xml")

    elif call_info is None:
        # Call was ended/rejected
        print(f"[Twilio Wait] Call {sid} not found — hanging up")
        return Response(content="""<?xml version="1.0" encoding="UTF-8"?>
<Response><Hangup/></Response>""", media_type="application/xml")

    else:
        # Still ringing, or accepted but the voice engine isn't ready yet —
        # play hold and re-poll in 3 seconds
        wait_url = f"{SERVER_URL.rstrip('/') if SERVER_URL else ''}/api/call/wait?callSid={sid}"
        twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Play loop="1">https://demo.twilio.com/docs/classic.mp3</Play>
    <Redirect method="POST">{wait_url}</Redirect>
</Response>"""
        return Response(content=twiml, media_type="application/xml")

class AcceptCallRequest(BaseModel):
    roomName: str
    agentIdentity: str

@app.post("/api/call/accept")
async def call_accept(request: AcceptCallRequest):
    """
    Triggered when an agent accepts an incoming call.
    - Sets call status to 'accepted' so /api/call/wait stops holding and bridges to LiveKit SIP.
    - Returns LiveKit access token for the agent to join the room.
    """
    room_name = request.roomName
    print(f"[Call Accept] Agent {request.agentIdentity} accepting room={room_name}")

    if room_name in active_calls:
        # Mark as 'accepted' — /api/call/wait polls this and will then bridge the SIP call
        active_calls[room_name]["status"] = "accepted"
        print(f"[Call Accept] Status set to 'accepted' for room={room_name}")
    else:
        print(f"[Call Accept] WARNING: room {room_name} not found in active_calls — call may have already ended")

    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        raise HTTPException(status_code=500, detail="LiveKit server keys are not configured.")

    # Fire-and-forget: unsubscribe the inbound SIP caller from the raw agent mic so
    # they only hear the bot's converted Keira voice. For inbound calls the SIP
    # participant identity is the caller's phone number (From field), but LiveKit
    # names them by their From URI — we scan by exclusion instead of hardcoded identity.
    # The helper retries until the agent browser joins and publishes their mic track.
    asyncio.create_task(_restrict_sip_audio(room_name, sip_identity="sip-caller"))

    # Generate access token for the agent
    agent_token = api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET) \
        .with_identity(request.agentIdentity) \
        .with_name(f"Agent {request.agentIdentity}") \
        .with_grants(api.VideoGrants(
            room_join=True,
            room=room_name,
            can_publish=True,
            can_subscribe=True
        )) \
        .with_ttl(datetime.timedelta(seconds=3600))

    return {
        "status": "accepted",
        "roomName": room_name,
        "token": agent_token.to_jwt(),
        "serverUrl": LIVEKIT_URL
    }

class EndCallRequest(BaseModel):
    roomName: str

@app.post("/api/call/end")
async def call_end(request: EndCallRequest):
    """
    Disconnects the bot, deletes the LiveKit room, and broadcasts the disconnect event.
    """
    room_name = request.roomName

    # 1. Stop the voice conversion bot
    worker = active_workers.get(room_name)
    if worker:
        await worker.stop()
        active_workers.pop(room_name, None)

    # 2. Programmatically close the LiveKit Room (disconnects all participants)
    if LIVEKIT_API_KEY and LIVEKIT_API_SECRET:
        try:
            lk = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
            await lk.room.delete_room(api.DeleteRoomRequest(room=room_name))
            await lk.aclose()
            print(f"[Server] Programmatically deleted LiveKit room: {room_name}")
        except Exception as e:
            print(f"[Server Error deleting room] {e}")

    # 3. Twilio client hangup fallback (inbound calls have a Twilio CallSid).
    # Outbound calls are LiveKit-originated SIP — there is no Twilio CallSid.
    # Those are ended by deleting the LiveKit room (step 2 above).
    if twilio_client and room_name in active_calls:
        call_info = active_calls[room_name]
        if call_info.get("direction") == "inbound" and "call_sid" in call_info:
            try:
                twilio_client.calls(call_info["call_sid"]).update(status="completed")
                print(f"[Server] Twilio CallSid {call_info['call_sid']} hung up programmatically")
            except Exception as e:
                print(f"[Server Error hanging up Twilio call] {e}")

    # 4. Broadcast end call to agents
    await manager.broadcast({
        "event": "call_ended",
        "roomName": room_name
    })

    active_calls.pop(room_name, None)
    return {"status": "ended", "roomName": room_name}

@app.get("/api/call/status")
async def call_status(roomName: str = None):
    """
    Returns status of active calls.
    """
    if roomName:
        if roomName in active_calls:
            return active_calls[roomName]
        raise HTTPException(status_code=404, detail="Call not found")
    return {"active_calls": list(active_calls.values())}

# --- TWILIO + LIVEKIT SETUP & HEALTH ENDPOINTS ---

@app.get("/api/health")
async def health_check():
    """
    Returns the configuration and live status of all integrations.
    Check this after deployment to confirm everything is wired up correctly.
    """
    return {
        "livekit": {
            "url": LIVEKIT_URL,
            "api_key_set": bool(LIVEKIT_API_KEY),
            "api_secret_set": bool(LIVEKIT_API_SECRET),
        },
        "twilio": {
            "account_sid_set": bool(TWILIO_ACCOUNT_SID),
            "auth_token_set": bool(TWILIO_AUTH_TOKEN),
            "phone_number": TWILIO_PHONE_NUMBER or "not set",
            "sip_uri": TWILIO_SIP_URI or "not set",
            "client_initialized": bool(twilio_client),
        },
        "livekit_sip": {
            "outbound_trunk_id": TWILIO_SIP_TRUNK_ID or "not set — run POST /api/setup",
            "inbound_webhook": f"{SERVER_URL}/api/call/inbound" if SERVER_URL else "SERVER_URL not set",
            "sip_domain": get_livekit_sip_domain(),
        },
        "rvc": {
            "endpoint": RVC_ENDPOINT_URL or "not configured (using dummy converter)",
        },
        "server_url": SERVER_URL or "not set",
        "active_calls": len(active_calls),
        "active_bots": len(active_workers),
    }

@app.post("/api/setup")
async def setup_integrations():
    """
    One-time setup endpoint. Call this once after filling in all credentials.

    It will:
      1. Create a LiveKit SIP Outbound Trunk connecting LiveKit → Twilio → PSTN
      2. Configure your Twilio phone number's inbound webhook to point to this server

    After running this, copy the returned trunk_id and save it as TWILIO_SIP_TRUNK_ID
    in your Render dashboard, then redeploy.
    """
    import traceback as _tb

    results = {}
    errors = {}

    # Step 1: Create LiveKit SIP Outbound Trunk
    if not TWILIO_SIP_URI:
        errors["livekit_sip_trunk"] = "TWILIO_SIP_URI is not set. Set it to your Twilio Elastic SIP Trunk termination URI (e.g. myproject.pstn.twilio.com)."
    elif not all([TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER]):
        errors["livekit_sip_trunk"] = "Missing TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, or TWILIO_PHONE_NUMBER."
    elif not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        errors["livekit_sip_trunk"] = "Missing LIVEKIT_API_KEY or LIVEKIT_API_SECRET."
    else:
        lk = None
        try:
            lk = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)

            # Check if trunk already exists to avoid recreating it on every /api/setup call.
            # Recreating the trunk changes its ID, which breaks the TWILIO_SIP_TRUNK_ID env var
            # and causes a 404 "object cannot be found" on the next outbound call.
            existing = await lk.sip.list_outbound_trunk(api.ListSIPOutboundTrunkRequest())
            existing_trunk = next((t for t in existing.items if t.name == "Keira Twilio Outbound"), None)

            clean_phone = TWILIO_PHONE_NUMBER.replace(" ", "")

            if existing_trunk:
                # Reuse the existing trunk — its ID is stable and the env var stays valid.
                trunk_id = existing_trunk.sip_trunk_id
                print(f"[Setup] Reusing existing LiveKit SIP Outbound Trunk: {trunk_id}")
                results["livekit_sip_trunk"] = {
                    "status": "already_exists",
                    "trunk_id": trunk_id,
                    "address": existing_trunk.address,
                    "numbers": list(existing_trunk.numbers),
                    "note": "Trunk already exists and was reused. TWILIO_SIP_TRUNK_ID env var remains valid.",
                }
            else:
                trunk_info = api.SIPOutboundTrunkInfo(
                    name="Keira Twilio Outbound",
                    address=TWILIO_SIP_URI,
                    numbers=[clean_phone],
                    auth_username=TWILIO_SIP_USERNAME,
                    auth_password=TWILIO_SIP_PASSWORD,
                )
                created = await lk.sip.create_outbound_trunk(
                    api.CreateSIPOutboundTrunkRequest(trunk=trunk_info)
                )
                trunk_id = created.sip_trunk_id
                print(f"[Setup] Created LiveKit SIP Outbound Trunk: {trunk_id} with number {clean_phone}")
                results["livekit_sip_trunk"] = {
                    "status": "created",
                    "trunk_id": trunk_id,
                    "address": TWILIO_SIP_URI,
                    "numbers": [clean_phone],
                    "action": f"Save TWILIO_SIP_TRUNK_ID={trunk_id} in your Render env vars then redeploy",
                }
        except Exception as e:
            _tb.print_exc()
            errors["livekit_sip_trunk"] = str(e)
        finally:
            if lk:
                await lk.aclose()

    # Step 2: Configure Twilio phone number inbound webhook
    if not SERVER_URL:
        errors["twilio_webhook"] = "SERVER_URL is not set. Set it to your public server URL (e.g. https://keira-backend.onrender.com)."
    elif not twilio_client:
        errors["twilio_webhook"] = "Twilio client not initialized — check TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN."
    elif not TWILIO_PHONE_NUMBER:
        errors["twilio_webhook"] = "TWILIO_PHONE_NUMBER is not set."
    else:
        try:
            webhook_url = f"{SERVER_URL.rstrip('/')}/api/call/inbound"
            numbers = twilio_client.incoming_phone_numbers.list(phone_number=TWILIO_PHONE_NUMBER)
            if not numbers:
                errors["twilio_webhook"] = f"Phone number {TWILIO_PHONE_NUMBER} not found in your Twilio account."
            else:
                numbers[0].update(voice_url=webhook_url, voice_method="POST")
                print(f"[Setup] Twilio webhook configured: {webhook_url}")
                results["twilio_webhook"] = {
                    "status": "configured",
                    "phone_number": TWILIO_PHONE_NUMBER,
                    "webhook_url": webhook_url,
                }
        except Exception as e:
            _tb.print_exc()
            errors["twilio_webhook"] = str(e)

    # Steps 3+4: Clean up old SIP trunks/rules and recreate them linked to each other.
    # The old "twilioinbound" trunk may have IP/auth restrictions that block Twilio PV.
    # We delete everything and recreate a permissive trunk + a dispatch rule that
    # explicitly targets only that trunk so there is no ambiguity.
    inbound_trunk_id = None
    if not LIVEKIT_API_KEY or not LIVEKIT_API_SECRET:
        errors["sip_inbound_trunk"] = "Missing LIVEKIT_API_KEY or LIVEKIT_API_SECRET."
        errors["sip_dispatch_rule"] = "Missing LIVEKIT_API_KEY or LIVEKIT_API_SECRET."
    else:
        lk = None
        try:
            lk = api.LiveKitAPI(LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET)

            # --- Inbound trunk ---
            existing_trunks = await lk.sip.list_inbound_trunk(api.ListSIPInboundTrunkRequest())
            keira_trunk = None
            deleted_trunks = []
            for t in existing_trunks.items:
                if t.name == "Keira Twilio Inbound":
                    keira_trunk = t
                else:
                    # Delete any other inbound trunk (e.g. old "twilioinbound") that
                    # may have IP ACLs or auth requirements blocking Twilio PV calls.
                    try:
                        await lk.sip.delete_trunk(api.DeleteSIPTrunkRequest(sip_trunk_id=t.sip_trunk_id))
                        deleted_trunks.append(t.sip_trunk_id)
                        print(f"[Setup] Deleted conflicting inbound trunk: {t.sip_trunk_id} ({t.name})")
                    except Exception:
                        pass

            if keira_trunk is None:
                keira_trunk = await lk.sip.create_inbound_trunk(
                    api.CreateSIPInboundTrunkRequest(
                        trunk=api.SIPInboundTrunkInfo(
                            name="Keira Twilio Inbound",
                            # No auth or IP restrictions — Twilio Programmable Voice
                            # sends SIP without pre-shared credentials.
                        )
                    )
                )
                print(f"[Setup] Created SIP inbound trunk: {keira_trunk.sip_trunk_id}")

            inbound_trunk_id = keira_trunk.sip_trunk_id
            results["sip_inbound_trunk"] = {
                "status": "ready",
                "trunk_id": inbound_trunk_id,
                "deleted_conflicting": deleted_trunks,
            }

            # --- Dispatch rule ---
            existing_rules = await lk.sip.list_dispatch_rule(api.ListSIPDispatchRuleRequest())
            deleted_rules = []
            for r in existing_rules.items:
                # Delete ALL existing rules so we can recreate fresh with correct trunk_id
                try:
                    await lk.sip.delete_dispatch_rule(
                        api.DeleteSIPDispatchRuleRequest(sip_dispatch_rule_id=r.sip_dispatch_rule_id)
                    )
                    deleted_rules.append(r.sip_dispatch_rule_id)
                    print(f"[Setup] Deleted old dispatch rule: {r.sip_dispatch_rule_id} ({r.name})")
                except Exception:
                    pass

            rule = await lk.sip.create_dispatch_rule(
                api.CreateSIPDispatchRuleRequest(
                    rule=api.SIPDispatchRule(
                        dispatch_rule_callee=api.SIPDispatchRuleCallee(
                            room_prefix="",
                            randomize=False,
                        )
                    ),
                    # Restrict to only our permissive trunk so the old "twilioinbound"
                    # trunk cannot intercept calls first.
                    trunk_ids=[inbound_trunk_id],
                    name="Keira Inbound Routing",
                )
            )
            print(f"[Setup] Created SIP dispatch rule: {rule.sip_dispatch_rule_id}")
            results["sip_dispatch_rule"] = {
                "status": "created",
                "rule_id": rule.sip_dispatch_rule_id,
                "trunk_id": inbound_trunk_id,
                "deleted_old_rules": deleted_rules,
            }

        except Exception as e:
            _tb.print_exc()
            errors["sip_setup"] = str(e)
        finally:
            if lk:
                await lk.aclose()

    overall_ok = not errors
    return {
        "ok": overall_ok,
        "results": results,
        "errors": errors,
    }

# --- GPU KEEP-WARM ENDPOINT ---

@app.post("/api/warmup")
async def warmup_gpu():
    """
    Pings the RVC endpoint /health to ensure the T4 GPU is warm.
    Retries every 30 seconds for up to 6 minutes to handle Modal cold starts.
    """
    if not RVC_ENDPOINT_URL:
        print("[Server Warmup] FAILED: No RVC_ENDPOINT_URL configured in .env")
        return {"status": "skipped", "message": "No RVC endpoint URL configured."}

    return await _wait_for_rvc_ready(max_wait_seconds=360.0, poll_interval=30.0)

# --- GPU DEPLOY ENDPOINT ---

@app.post("/api/deploy")
async def deploy_gpu():
    """
    Executes 'modal deploy modal_deploy/worker.py' to deploy the RVC worker to Modal.
    Requires MODAL_TOKEN_ID and MODAL_TOKEN_SECRET to be configured in Render's environment variables.
    """
    import subprocess
    import os
    
    # Check if Modal tokens are present
    token_id = os.getenv("MODAL_TOKEN_ID")
    token_secret = os.getenv("MODAL_TOKEN_SECRET")
    
    if not token_id or not token_secret:
        return {
            "status": "error",
            "message": "MODAL_TOKEN_ID or MODAL_TOKEN_SECRET environment variables are missing on Render."
        }
        
    print("[Server Deploy] Triggering modal deploy modal_deploy/worker.py...")
    try:
        def run_deploy():
            # Build env variables with path overrides to find the modal executable
            env = os.environ.copy()
            # Try to run modal deploy
            res = subprocess.run(
                ["modal", "deploy", "modal_deploy/worker.py"],
                capture_output=True,
                text=True,
                env=env,
                cwd=os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
            )
            return res
            
        res = await asyncio.to_thread(run_deploy)
        print(f"[Server Deploy] STDOUT: {res.stdout}")
        print(f"[Server Deploy] STDERR: {res.stderr}")
        
        if res.returncode == 0:
            return {
                "status": "success",
                "message": "Modal GPU deployed successfully!",
                "output": res.stdout
            }
        else:
            return {
                "status": "error",
                "message": f"Deployment failed: {res.stderr or res.stdout}",
                "output": res.stdout
            }
    except Exception as e:
        import traceback
        traceback.print_exc()
        return {
            "status": "error",
            "message": f"Deployment exception: {str(e)}"
        }

# --- WEBSOCKET SIGNALING ROUTE ---


@app.websocket("/api/call/ws")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    try:
        while True:
            # Maintain active connection and listen for client-side pings
            data = await websocket.receive_text()
            if data == "ping":
                await websocket.send_json({"event": "pong"})
    except WebSocketDisconnect:
        manager.disconnect(websocket)
    except Exception:
        manager.disconnect(websocket)

# --- FRONTEND ROUTING ---

# Mount static frontend files if directory exists
frontend_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend"))
if os.path.exists(frontend_path):
    app.mount("/", StaticFiles(directory=frontend_path, html=True), name="frontend")
else:
    @app.get("/")
    async def fallback_root():
        return {"message": "Keira MVP Server Running. Frontend static files directory is missing."}
